/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ahmad
 */
public class form1 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
        displayPassengers();
        setComponentName();
    }
    private void setComponentName()
    {
        b2.setName("b2");
        b1.setName("b1");
        b3.setName("b3");
        l1.setName("l1");
        l2.setName("l2");
        l3.setName("l3");
        t1.setName("t1");
        t2.setName("t2");
        t3.setName("t3");
        t4.setName("t4");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pgen = new javax.swing.JLabel();
        pticketid = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Pname = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        paddress = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        b2 = new javax.swing.JButton();
        Pgendercb = new javax.swing.JComboBox<>();
        l2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        passengertable = new javax.swing.JTable();
        b3 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        pnumber = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        Pstatuscb = new javax.swing.JComboBox<>();
        Pstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pgen.setBackground(new java.awt.Color(0, 0, 0));
        Pgen.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Pgen.setForeground(new java.awt.Color(255, 51, 51));
        Pgen.setText("GENDER");

        pticketid.setBackground(new java.awt.Color(0, 0, 0));
        pticketid.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pticketid.setForeground(new java.awt.Color(255, 0, 51));
        pticketid.setText("TICKET ID");

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        Pname.setBackground(new java.awt.Color(0, 0, 0));
        Pname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Pname.setForeground(new java.awt.Color(255, 0, 51));
        Pname.setText("PERSON NAME");

        b1.setBackground(new java.awt.Color(255, 0, 51));
        b1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 0, 0));
        b1.setText("EDIT");
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        t2.setBackground(new java.awt.Color(102, 0, 0));
        t2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 204, 51));
        t2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 0, 51));
        l1.setText("FAST TOUR COMPANY");

        l3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 0, 51));
        l3.setText("LIST OF PASSENGERS");

        paddress.setBackground(new java.awt.Color(0, 0, 0));
        paddress.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        paddress.setForeground(new java.awt.Color(255, 0, 51));
        paddress.setText("ADDRESS");

        t1.setBackground(new java.awt.Color(102, 0, 0));
        t1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 204, 51));
        t1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(255, 0, 51));
        b2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(51, 0, 0));
        b2.setText("DELETE");
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        Pgendercb.setBackground(new java.awt.Color(102, 0, 0));
        Pgendercb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pgendercb.setForeground(new java.awt.Color(255, 204, 51));
        Pgendercb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE ", "ANY" }));
        Pgendercb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PgendercbActionPerformed(evt);
            }
        });

        l2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 0, 51));
        l2.setText("MANAGE PASSENGERS");

        passengertable.setBackground(new java.awt.Color(102, 0, 0));
        passengertable.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        passengertable.setForeground(new java.awt.Color(255, 204, 51));
        passengertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        passengertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passengertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(passengertable);

        b3.setBackground(new java.awt.Color(255, 0, 51));
        b3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(51, 0, 0));
        b3.setText("RETURN");
        b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        t3.setBackground(new java.awt.Color(102, 0, 0));
        t3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        t3.setForeground(new java.awt.Color(255, 204, 51));
        t3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        pnumber.setBackground(new java.awt.Color(0, 0, 0));
        pnumber.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pnumber.setForeground(new java.awt.Color(255, 0, 51));
        pnumber.setText("PHONE NO");

        t4.setBackground(new java.awt.Color(102, 0, 0));
        t4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        t4.setForeground(new java.awt.Color(255, 204, 51));
        t4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        Pstatuscb.setBackground(new java.awt.Color(102, 0, 0));
        Pstatuscb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pstatuscb.setForeground(new java.awt.Color(255, 204, 51));
        Pstatuscb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE", "MARRIED" }));

        Pstatus.setBackground(new java.awt.Color(0, 0, 0));
        Pstatus.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Pstatus.setForeground(new java.awt.Color(255, 0, 51));
        Pstatus.setText("STATUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pname)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pstatus)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pstatuscb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pgen)
                                    .addComponent(Pgendercb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pticketid, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)))))
                .addGap(341, 341, 341))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paddress)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnumber)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l3)
                        .addGap(342, 342, 342))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(l1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pname)
                            .addComponent(pticketid)
                            .addComponent(paddress)
                            .addComponent(pnumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pgen)
                            .addComponent(Pstatus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Pgendercb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Pstatuscb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con=null;
    PreparedStatement put=null;
    ResultSet rs=null,rs1=null;
    Statement s=null,s1=null;
       
    private void displayPassengers()
    {
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3307/tourdb","root","arsenal360");
            s=con.createStatement();
            rs=s.executeQuery("select * from passengertable");
            passengertable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
        }
        
    }
    int passid=0;
    private void countpassengers()
    {
        try
        {
            s1=con.createStatement();
            rs1=s1.executeQuery("select MAX(Pid) from passengertable");
            rs1.next(); 
            passid=rs1.getInt(1)+1; 
        }catch(Exception e){
            
        }    
    }
    private void clear()
    {
        t1.setText("");
        t4.setText("");
        t3.setText("");
        t2.setText("");
        
    }
    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        
    }//GEN-LAST:event_b1MouseClicked
    int key=0;
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(key==0)
        {
            JOptionPane.showMessageDialog(this, "select a passenger ");
        }
        else
        {
            try
            {
                //countpassengers();
                con=DriverManager.getConnection("jdbc:mysql://localhost:3307/tourdb","root","arsenal360");
                String query="update passengertable set Pname=?,Pnat=?,Pgen=?,Ppass=?,Padd=?,Pphone=? where Pid=?";
                PreparedStatement add=con.prepareStatement(query);
                add.setInt(7,key  );
                add.setString(1, t1.getText());
                add.setString(2,Pstatuscb.getSelectedItem().toString());
                add.setString(3,Pgendercb.getSelectedItem().toString());
                add.setString(4,t2.getText());
                add.setString(5, t3.getText());
                add.setString(6, t4.getText());
                int row=add.executeUpdate();
                JOptionPane.showMessageDialog(this, "passenger is edited ");
                con.close();
                displayPassengers();
                clear();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e );
            }
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        if(t1.getText().isEmpty() || t3.getText().isEmpty() || t4.getText().isEmpty() || t2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"OOops!!! Some Information is Missing");
        }
        else
        {

        }
    }//GEN-LAST:event_b2MouseClicked

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(key==0)
        {
            JOptionPane.showMessageDialog(this, "select a passenger" );
        }
        else
        {
            try
            {
                con=DriverManager.getConnection("jdbc:mysql://localhost:3307/tourdb","root","arsenal360");
                String query="delete from passengertable where Pid="+key;
                Statement delete=con.createStatement();
                delete.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "passenger deleted");
                displayPassengers();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e );
            }
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void PgendercbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PgendercbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PgendercbActionPerformed

    private void passengertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengertableMouseClicked
        DefaultTableModel model=(DefaultTableModel)passengertable.getModel();
        int myindex=passengertable.getSelectedRow();
        key=Integer.valueOf(model.getValueAt(myindex,0).toString());
        t1.setText(model.getValueAt(myindex,1).toString());
        Pstatuscb.setSelectedItem(model.getValueAt(myindex,2).toString());
        Pgendercb.setSelectedItem(model.getValueAt(myindex,3).toString());
        t2.setText(model.getValueAt(myindex,4).toString());
        t3.setText(model.getValueAt(myindex,5).toString());
        t4.setText(model.getValueAt(myindex,6).toString());

    }//GEN-LAST:event_passengertableMouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        new FORM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b3MouseClicked

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        new FORM().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pgen;
    private javax.swing.JComboBox<String> Pgendercb;
    private javax.swing.JLabel Pname;
    private javax.swing.JLabel Pstatus;
    private javax.swing.JComboBox<String> Pstatuscb;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel paddress;
    private javax.swing.JTable passengertable;
    private javax.swing.JLabel pnumber;
    private javax.swing.JLabel pticketid;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
